modLoader="kotlinforforge"
loaderVersion="[1.7,)"
license="MIT License"
issueTrackerURL="https://github.com/exzhawk/NonImmersiveHud/issues"
[[mods]]
modId="nonimmersivehud"
version="${file.jarVersion}"
displayName="Non Immersive HUD"
authors="Epix Zhang"
description='''
Make you HUD(Hwyla) not immersive anymore, Access the HUD in a web page.
'''
[[dependencies.nonimmersivehud]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nonimmersivehud]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nonimmersivehud]]
    modId="kotlinforforge"
    mandatory=false
    versionRange="[1.6.2,)" #todo   bump to 1.7.0 or above
    ordering="AFTER"
    side="CLIENT"
[[dependencies.nonimmersivehud]]
    modId="waila"
    mandatory=true
    versionRange="[1.10.10,)"
    ordering="AFTER"
    side="CLIENT"
